#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -s "${BASEDIR}/.gitignore" ~
ln -s "${BASEDIR}/.tmux.conf" ~
ln -s "${BASEDIR}/.vim" ~
ln -s "${BASEDIR}/.vimrc" ~
ln -s "${BASEDIR}/.zsh_aliases" ~
ln -s "${BASEDIR}/.zshrc" ~
ln -s "${BASEDIR}/.inputrc" ~
ln -s "${BASEDIR}/.irbrc" ~
ln -s "${BASEDIR}/.tigrc" ~

mkdir -p ~/.zsh

ln -s "${BASEDIR}/.zsh/_git" ~/.zsh

# if [[ $REMOTE_CONTAINERS ]]; then
#   # TODO call function with "${BASEDIR}/.gitconfig.thinkific"
#   ln -s "${BASEDIR}/.gitconfig.thinkific" ~/.gitconfig
# else
  ln -s "${BASEDIR}/.zsh/_pass" ~/.zsh
  ln -s "${BASEDIR}/.gitconfig" ~
  # TODO call function with "${BASEDIR}/.gitconfig"
# fi

# TODO this needs to be a function
# sed -n '/# SNIP/q;p' ~/.gitconfig > /tmp/.gitconfig.tmp
# cat ~/tmp/.gitconfig.tmp > ~/.gitconfig
# cat "${BASEDIR}/.gitconfig.thinkific" >> ~/.gitconfig
