#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -s "${BASEDIR}/.gitignore" ~
ln -s "${BASEDIR}/.tmux.conf" ~
ln -s "${BASEDIR}/.vim" ~
ln -s "${BASEDIR}/.vimrc" ~
ln -s "${BASEDIR}/.zsh_aliases" ~
ln -s "${BASEDIR}/.zshrc" ~
ln -s "${BASEDIR}/.inputrc" ~
ln -s "${BASEDIR}/.irbrc" ~
ln -s "${BASEDIR}/.tigrc" ~

mkdir -p ~/.zsh

ln -s "${BASEDIR}/.zsh/_git" ~/.zsh

if [[ -f /.dockerenv ]]; then
  # in a container

  ln -s "${BASEDIR}/.gitconfig.trustflight" ~

  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  brew install tmux zsh fzf

  # apt-get update
  # apt-get -y install tmux zsh

  # git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  # ~/.fzf/install --key-bindings --completion --update-rc
else
  # outside of a container

  ln -s "${BASEDIR}/.gitconfig" ~
  ln -s "${BASEDIR}/.zsh/_pass" ~/.zsh
fi
