#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -s "${BASEDIR}/.gitconfig" ~
ln -s "${BASEDIR}/.gitignore" ~
ln -s "${BASEDIR}/.tmux.conf" ~
ln -s "${BASEDIR}/.vim" ~
ln -s "${BASEDIR}/.vimrc" ~
ln -s "${BASEDIR}/.zsh_aliases" ~
ln -s "${BASEDIR}/.zshrc" ~

mkdir -p "$HOME/.zsh"
git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
